### PR TITLE
Extend socket timeout and Address a runtime error

### PR DESCRIPTION
**Pull request by Grossdm**
The socket timeout appears to be global, so this may be a better adjustment.

I also had one or two errors that the decode utf-8 on the filename seemed to resolve. This is basically a "try and see" change.

### CODE REVIEW

**Review by Amelandbor — COMMENTED** [review]
Do you mean the timeout is set in the common subtitles plugin? Otherwise I don't see an advantage to add extra code?

**Comment by Grossdm** [comment]
You've run into my ignorance with "common subtitles plugin" - I don't know what this is.
I had just found that the timeout was a global setting, and it was advised to put it back if you changed it, e.g https://fedorahosted.org/suds/ticket/403.

**Comment by Amelandbor** [comment]
I mean the subtitles plugin of kodi. This is a service added to that
plugin.

But I think kodi is using a higher python version.

Op 21 dec. 2016 6:29 p.m. schreef "Doug" <notifications@github.com>:

You've run into my ignorance with "common subtitles plugin" - I don't know
what this is.
I had just found that the timeout was a global setting, and it was advised
to put it back if you changed it, e.g https://fedorahosted.org/suds/
ticket/403.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Amelandbor/service.subtitles.addic7ed/pull/8#issuecomment-268585344>,
or mute the thread

**Comment by Grossdm** [comment]
@Amelandbor , did you have any thoughts on the unicode mod for `item['filename']` ?

It has been so long ago that I changed it in my Kodi installations that I'm not certain how I arrived at it.  I must have had an error, turned on debugging, and proceeded from there.

As I'm sure you've noticed, I am not exactly what you would call a "developer". :stuck_out_tongue_winking_eye:

**Comment by Amelandbor** [comment]
I'm not exactly sure if it's necessary to be honest. I'm also not a python developer, but from the code it doesn't seem like it's necessary. Do you still have errors with the latest code, where the timeout was changed to 20?

**Comment by Grossdm** [comment]
@Amelandbor , thank you and I'll reserve the right to be "creative" in describing my experience. :+1: 

Actually, I had made both of these changes months before you posted your change to the timeout.

I do still encounter errors. These only occur after I've had Kodi running for quite a while, i.e. after I've watched several things and used Addic7ed subtitles with each video. I have not tried to troubleshoot these errors yet.

**Comment by Amelandbor** [comment]
That sounds like it could be the amount of free Addic7ed subtitles you can download per day.

I'm going to keep the code as it is right now, but if you or someone else has problems, please open a new issue with a debug log.

**Comment by Grossdm** [comment]
@Amelandbor , I find that quitting and starting Kodi resolves the issues that I just mentioned.  This clearly suggests that it's not a quota problem.
I'll try to get a debug log at some point.

Do you specify a directory for subtitles in Kodi?  I'm don't think that I've ever seen this actually change anything.

**Comment by Amelandbor** [comment]
Yeah, that seems to be another problem.

The subtitle is saved in the same directory as the video file it is
playing. There is a temporary file created before that somewhere in the
kodi user directory.

Op 22 dec. 2016 6:41 p.m. schreef "Doug" <notifications@github.com>:

**Comment by Grossdm** [comment]
@Amelandbor , I didn't get a sense of your opinion on the unicode mod.  I suppose this is because I don't recall the error(s) that it seemed to resolve?

Assuming you don't see a benefit to this mod, should a click the "Delete branch" button? :anguished:

**Comment by Amelandbor** [comment]
Yeah, sorry, but it seems to me it should use the exact same filename as
the video file it is searching for.

You can keep the branch if you want to. I closed the pull request for now,
but you can always make a new one if you have other changes or when the
unicode needs to be pulled in anyway.

Op 22 dec. 2016 7:08 p.m. schreef "Doug" <notifications@github.com>:

**Comment by Grossdm** [comment]
I've read some about unicode in Kodi, and it is not easy to follow.  Perhaps some of my confusion on the matter is that I've looked through my installed addons for examples, and devs have their own way of handling unicode (often with wrapper functions).

**Comment by Amelandbor** [comment]
Yeah I don't know exactly, but it does not seem to be breaking anything on
my end. But maybe it should be implemented later on if there are some
issues with it.

Op 22 dec. 2016 8:06 p.m. schreef "Doug" <notifications@github.com>:

**Pull request closed without merging**
